[project]
name = "common"
version = "0.1.0"
description = "Shared utilities for MCP tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
packages = [
  { include = "common", from = "src/common" }
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"